# Generated by Django 4.2.8 on 2024-02-21 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('no_plate', models.CharField(max_length=150)),
                ('seats', models.IntegerField()),
                ('departure_city', models.CharField(max_length=150)),
                ('departure_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=150)),
                ('distance', models.FloatField()),
                ('timeTaken', models.DurationField()),
                ('buses', models.ManyToManyField(related_name='routes', to='managements.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departTime', models.DateTimeField()),
                ('arrivalTime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=50)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passengerAge', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('booking_history', models.ManyToManyField(blank=True, to='managements.ticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(max_length=100)),
                ('transactionId', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.ticket')),
            ],
        ),
    ]
