# Generated by Django 4.2.10 on 2024-02-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.DateField(),
        ),
    ]
