# Generated by Django 4.2.11 on 2024-03-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0009_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(unique=True)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='ticket',
            name='pay',
            field=models.IntegerField(choices=[(1500, 1500), (1700, 1700), (1800, 1800), (1900, 1900), (20000, 20000)], null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(choices=[('AIRTEL MOBILE', 'AIRTEL MOBILE'), ('ATM', 'ATM'), ('BANK TRANSFER', 'BANK TRANSFER'), ('MPESA', 'MPESA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_city',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Mombasa', 'Mombasa'), ('Nakuru', 'Nakuru'), ('Siaya', 'Siaya'), ('Meru', 'Meru'), ('Kisii', 'Kisii'), ('Narok', 'Narok'), ('Nyeri', 'Nyeri'), ('Thika', 'Thika'), ('Turkana', 'Turkana')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_city',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Mombasa', 'Mombasa'), ('Nakuru', 'Nakuru'), ('Siaya', 'Siaya'), ('Meru', 'Meru'), ('Kisii', 'Kisii'), ('Narok', 'Narok'), ('Nyeri', 'Nyeri'), ('Thika', 'Thika'), ('Turkana', 'Turkana')], max_length=150),
        ),
    ]
