# Generated by Django 4.2.10 on 2024-03-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0010_seat_delete_booking_ticket_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
