# Generated by Django 4.2.10 on 2024-03-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0012_alter_bus_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='is_available',
            field=models.BooleanField(null=True, verbose_name='is_available'),
        ),
    ]
