# Generated by Django 4.2.10 on 2024-03-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0014_alter_bus_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pay',
            field=models.IntegerField(choices=[(1500, 1500), (1700, 1700)], null=True),
        ),
    ]
