# Generated by Django 4.2.10 on 2024-03-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0015_alter_ticket_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.bus'),
        ),
    ]
